# Generated by Django 5.2.1 on 2025-06-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apply',
            table='applications',
        ),
    ]
