# Generated by Django 5.2.1 on 2025-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('portfolio', models.IntegerField()),
                ('get_warranty', models.IntegerField()),
            ],
            options={
                'db_table': 'visitors',
                'managed': True,
            },
        ),
    ]
